### ISSUE TITLE
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<PREFIX>_users WHERE email = '<EMAIL ADDRESS>'' at line 1

### ISSUE THREAD

**Issue by SugarD-x** [StormlightTech/OpenCAD-php#351]
Every time I try to log in with an existing account, I receive the following error:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<PREFIX>_users WHERE email = '<EMAIL ADDRESS>'' at line 1`
(`<PREFIX>` = The board's prefix, and `<EMAIL ADDRESS>` = My email address).

No matter what I do, it refuses to cooperate. Tracing the code back, the login section that handles this hasn't changed in a year. No one else seems to be reporting this issue, so I'm at a loss. The syntax looks to be correct from what I can see. I also tried using a much simpler password for the hell of it that was only letters and numbers, and it didn't change anything.

If I try to log in with a non-existing account, I either get the same error, or the following one:
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<PREFIX>_departments' at line 1`

I'm not sure how to proceed, as I can't even log in with the only existing account. (This is happening after a fresh installation).

**Comment by mesl** [comment]
What MySQL version do you use? Could you please give me the query you'd like to use as well?

**Comment by SugarD-x** [comment]
It is MySQL Community Server 8.0.19. I'm not sure what the query would be for this. Unless I'm mistaken, it looks correct. I'm not sure why it is happening.

**Comment by mesl** [comment]
Did you define the email and prefix in the config? did you use the installer or did you manually configured it?

**Comment by SugarD-x** [comment]
I defined both, and I used the installer with default settings for the various CAD options.

**Comment by AtjonTV** [comment]
The issue seems to be either with the SQL Core inside OpenCAD to not resolve Placeholders correctly in Queries, or the config file having Placeholders instead of values in the variables (at least for the Table Prefix).

If you placed the Placeholders in your error messages, check your database if the tables exist.

Also, I can't remember OpenCAD being fully compatible with MySQL 8. So you could try a 5.x version.

(Please note that I will not check the code for this issue as I had a bad experience with the OpenCAD staff mid 2019, and I never want to either check for security loopholes or bugfixes ever again ;D )

**Comment by SugarD-x** [comment]
This appears to be fixed in the latest release as of this posting.

Thank you! :)
