### ISSUE TITLE
Driver License assign when Identity creation

### ISSUE THREAD

**Issue by AniTexs** [StormlightTech/OpenCAD-php#367]
**Describe the bug**
It is not possible to select valid from the list, it will automatically select the default MySQL "Unobtained" no matter what.
Also the PHP function used to split the dataset from the database on line 57 in publicFunctions.php is returning an array where the first (0) is and I quote ",'valid"
May have something to do with the trim.

**To Reproduce**
1. Go to Civilian Dashboard
2. Click on Create an Identity
3. Scroll down to Driver License Status
4. Select anything but Unobtained.

**Expected behavior**
That a user can set the specific status of their driver license

**Desktop (please complete the following information):**
 - Browser [Brave]

**Additional context**
It is not possible to change status either after this.
It posts the error that the user already exists.

**Comment by AniTexs** [comment]
Image of the edit problem
![image](https://user-images.githubusercontent.com/10406786/108839462-63eea480-75d5-11eb-9e91-3263fd580fb8.png)

Image showing the problem with the Statuses
![image](https://user-images.githubusercontent.com/10406786/108839582-897bae00-75d5-11eb-98d7-d1cc8c7d6395.png)

**Comment by ItsAGeekThing** [comment]
Hi @AniTexs,
Thanks for the report.

Any chance you can confirm the exact version of OpenCAD you are running (e.g., "_0.3.2-HOTFIX362_")?

Cheers,
Justin

**Comment by AniTexs** [comment]
0.3.2 Hotfix 362

**Comment by Austin-Wilsonn** [comment]
I am still getting this @AniTexs

**Comment by phillf** [comment]
I know exactly what this bug is. It's the function that strips the ")Yes" and random quote from the last and then explodes the list on the commas however it's stripping values aren't quite correct.

**Comment by phillf** [comment]
I fixed the trim problems however the DL stuff wasn't completely implemented before I left the project a few months ago. There was supposed to be a DMV dashboard which would allow for RP of the DMV. That needs to get done.

The idea is that the EU isn't supposed to have the ability to assign their own license status. A

As for the "Name Already Exists" thing.... I am not exactly sure why that is happening but I think it's trying to INSERT rather than UPDATE.

The answer to the trim problem is 27 and what is the Answer to the Ultimate Question of Life, the Universe, and Everything. (Enjoy your puzzle)
